apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: temporal
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: "4.0.1"
    serverImage: k8ssandra/cass-management-api:4.0.1
    telemetry:
      prometheus:
        enabled: true
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: civo-volume
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512M
    networking: 
      hostNetwork: true
    datacenters:
      - metadata:
          name: temporal
        size: 3
    mgmtAPIHeap: 256Mi 
  stargate:
    size: 1
    heapSize: 256M
    telemetry:
      prometheus:
        enabled: true
  reaper:
    keyspace: reaper_db
