apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kube-tarian/temporal-helm-charts.git
    targetRevision: HEAD
    path: temporal
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - createNamespace=true
    - pruneLast=true
