server:
  config:
    logLevel: "debug,info"
    numHistoryShards: 512
    persistence:
      default:
        driver: "cassandra"
        cassandra:
          hosts: ["temporal-temporal-service.k8ssandra-operator.svc.cluster.local"]
          port: 9042
          keyspace: temporal
          user: "temporal-superuser"
          existingSecret: "temporal-superuser"
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: ["temporal-temporal-service.k8ssandra-operator.svc.cluster.local"]
          port: 9042
          keyspace: temporal_visibility
          user: "temporal-superuser"
          existingSecret: "temporal-superuser"
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false


## set to true when the chart is set up for the first time, then set to false
schema:
  setup:
    enabled: true
  update:
    enabled: true
